import { getLang, tradThis } from '../../utils/translations.ts'
import { isStorageDefault } from '../../storage.ts'

import type { Sync } from '../../../types/sync.ts'

interface GistItem {
    url: string
    forks_url: string
    commits_url: string
    id: string
    node_id: string
    git_pull_url: string
    git_push_url: string
    html_url: string
    files: Record<string, GistFile>
    public: boolean
}

interface GistFile {
    filename: string
    type: string
    language: string
    raw_url: string
    size: number
}

export function setGistStatusNow(): void {
    const wrapper = document.getElementById('gist-sync-status-wrapper') as HTMLElement
    const base = document.getElementById('gist-sync-status-base') as HTMLSpanElement

    const dateString = new Date().toLocaleString(getLang(), {
        day: '2-digit',
        month: '2-digit',
        year: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
    })

    document.querySelector('#gist-sync-status')?.remove()

    const span = document.createElement('span')
    span.id = 'gist-sync-status'
    span.textContent = dateString
    wrapper?.appendChild(span)

    base.textContent = tradThis('Last update')
}

export async function setGistStatus(token?: string, id?: string): Promise<boolean> {
    const wrapper = document.getElementById('gist-sync-status-wrapper') as HTMLElement
    const base = document.getElementById('gist-sync-status-base') as HTMLSpanElement

    if (!token) {
        document.querySelector('#gist-sync-status')?.remove()
        base.textContent = tradThis('Waiting for authentification')
        return false
    }

    if (!id) {
        document.querySelector('#gist-sync-status')?.remove()
        base.textContent = tradThis('No saved data yet')
        return false
    }

    let resp: Response

    try {
        resp = await fetchGistWithTimeout(`https://api.github.com/gists/${id}`, { headers: gistHeaders(token) })
    } catch (_) {
        document.querySelector('#gist-sync-status')?.remove()
        base.textContent = tradThis('Cannot connect to GitHub')
        return false
    }

    if (!resp.ok) {
        document.querySelector('#gist-sync-status')?.remove()
        base.textContent = tradThis('No saved data yet')
        return false
    }

    const json = await resp.json()
    const isoDate = json.updated_at
    const dateString = new Date(isoDate).toLocaleString(getLang(), {
        day: '2-digit',
        month: '2-digit',
        year: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
    })

    document.querySelector('#gist-sync-status')?.remove()

    const link = document.createElement('a')
    link.id = 'gist-sync-status'
    link.href = json.html_url
    link.textContent = dateString

    wrapper?.appendChild(link)

    base.textContent = tradThis('Last update')

    return true
}

export async function retrieveGist(token: string, id?: string): Promise<Sync> {
    type GistGet = { files: Record<string, { content: string } | undefined> }

    if (!token) {
        throw new Error(GIST_ERROR.TOKEN)
    }
    if (!id) {
        throw new Error(GIST_ERROR.ID)
    }

    const req = await gistFetch(`https://api.github.com/gists/${id}`, {
        headers: gistHeaders(token),
    })

    const gist = (await req.json()) as GistGet
    const content = gist?.files?.[GIST_FILENAME]?.content

    if (!content) {
        throw new Error(GIST_ERROR.NOGIST)
    }

    try {
        return JSON.parse(content)
    } catch (_) {
        throw new Error(GIST_ERROR.JSON)
    }
}

export async function sendGist(token: string, id: string | undefined, data: Sync): Promise<string> {
    const description = 'File automatically generated by Bonjourr.'
    const files = { [GIST_FILENAME]: { content: JSON.stringify(data, undefined, 2) } }

    if (isStorageDefault(data)) {
        throw new Error(GIST_ERROR.DEFAULT)
    }

    // Create
    if (!id) {
        const resp = await gistFetch('https://api.github.com/gists', {
            body: JSON.stringify({ files, description, public: false }),
            headers: gistHeaders(token),
            method: 'POST',
        })

        const api = await resp.json()
        return api.id
    }

    if (isGistIdValid(id) === false) {
        throw new Error(GIST_ERROR.ID)
    }

    // Update
    await gistFetch(`https://api.github.com/gists/${id}`, {
        body: JSON.stringify({ files, description }),
        headers: gistHeaders(token),
        method: 'PATCH',
    }, { 404: GIST_ERROR.NOGIST })

    return id
}

export async function findGistId(token?: string): Promise<string | undefined> {
    if (!token) {
        throw new Error(GIST_ERROR.TOKEN)
    }

    const resp = await gistFetch('https://api.github.com/gists?per_page=100', {
        headers: gistHeaders(token),
    })

    const list = (await resp.json()) as GistItem[]
    const file = list.filter((gist) => !gist.public && gist.files[GIST_FILENAME]?.size > 0)[0]

    return file?.id
}

function isGistIdValid(id?: string): boolean {
    if (!id || id.length > 32) {
        return false
    }

    for (const char of id) {
        const code = char.charCodeAt(0)
        const isHex = (code >= 97 && code <= 102) || (code >= 48 && code <= 57)

        if (!isHex) {
            return false
        }
    }

    return true
}

function gistHeaders(token: string): HeadersInit {
    return {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
    }
}

async function fetchGistWithTimeout(input: RequestInfo, init?: RequestInit): Promise<Response> {
    const ms = init?.body ? GIST_WRITE_TIMEOUT_MS : GIST_READ_TIMEOUT_MS
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), ms)

    try {
        return await fetch(input, { ...init, signal: controller.signal })
    } finally {
        clearTimeout(timeout)
    }
}

async function gistFetch(
    input: RequestInfo,
    init?: RequestInit,
    statusOverrides?: Record<number, string>,
): Promise<Response> {
    let resp: Response
    let lastError: unknown

    for (let attempt = 0; attempt < GIST_MAX_RETRIES; attempt++) {
        if (attempt > 0) {
            await new Promise((r) => setTimeout(r, GIST_RETRY_DELAY_MS * attempt))
        }

        try {
            resp = await fetchGistWithTimeout(input, init)
        } catch (err) {
            lastError = err
            continue
        }

        if (resp.status >= 500) {
            lastError = new Error(GIST_ERROR.OTHER)
            continue
        }

        if (statusOverrides && resp.status in statusOverrides) {
            throw new Error(statusOverrides[resp.status])
        }
        if (resp.status === 401) {
            throw new Error(GIST_ERROR.TOKEN)
        }
        if (!resp.ok) {
            throw new Error(GIST_ERROR.OTHER)
        }

        return resp
    }

    throw lastError instanceof Error ? lastError : new Error(GIST_ERROR.NOCONN)
}

const GIST_MAX_RETRIES = 3
const GIST_RETRY_DELAY_MS = 1500
const GIST_READ_TIMEOUT_MS = 10000
const GIST_WRITE_TIMEOUT_MS = 30000
const GIST_FILENAME = 'bonjourr-export.json'

const GIST_ERROR = {
    ID: tradThis('Invalid Gist ID in settings.'),
    TOKEN: tradThis('Invalid token.'),
    NOGIST: tradThis('Bonjourr file not found in Gists.'),
    NOCONN: tradThis('Cannot connect to GitHub.'),
    JSON: tradThis('Invalid JSON response from GitHub.'),
    OTHER: tradThis('Unexpected GitHub Gist error.'),
    DEFAULT: tradThis('Tried to send default config.'),
}
